// Comprehensive built-in catalog of 30+ coding challenges
// Serves as an instant offline/local fallback when Firestore security rules are locked.

export const DEFAULT_PROBLEMS = [
  {
    id: "two-sum",
    title: "Two Sum",
    slug: "two-sum",
    difficulty: "Easy",
    tags: ["array", "hash-map"],
    description: "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.\n\nInput: First line is n (array size), second line has n space-separated integers, third line is the target.\nOutput: Two space-separated indices (0-indexed).",
    starter_code: {
      python: "n = int(input())\nnums = list(map(int, input().split()))\ntarget = int(input())\n# Write your solution below\n",
      cpp: "#include <iostream>\n#include <vector>\n#include <unordered_map>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    int target; cin >> target;\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int n; scanf(\"%d\", &n);\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    int target; scanf(\"%d\", &target);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        int target = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "4\n2 7 11 15\n9", expected_output: "0 1" },
      { input: "3\n3 2 4\n6", expected_output: "1 2" },
      { input: "2\n3 3\n6", expected_output: "0 1" },
    ],
  },
  {
    id: "palindrome-check",
    title: "Palindrome Check",
    slug: "palindrome-check",
    difficulty: "Easy",
    tags: ["string", "two-pointer"],
    description: "Given a string s, determine if it is a palindrome (reads the same forwards and backwards). Ignore case.\n\nInput: A single string.\nOutput: 'true' or 'false'.",
    starter_code: {
      python: "s = input().strip()\n# Write your solution below\n",
      cpp: "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s; getline(cin, s);\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\n#include <string.h>\nint main() {\n    char s[1001];\n    fgets(s, sizeof(s), stdin);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.nextLine().trim();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "racecar", expected_output: "true" },
      { input: "hello", expected_output: "false" },
      { input: "Madam", expected_output: "true" },
    ],
  },
  {
    id: "reverse-integer",
    title: "Reverse Integer",
    slug: "reverse-integer",
    difficulty: "Medium",
    tags: ["math"],
    description: "Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range [-2^31, 2^31 - 1], return 0.\n\nInput: A single integer x.\nOutput: The reversed integer or 0.",
    starter_code: {
      python: "x = int(input())\n# Write your solution below\n",
      cpp: "#include <iostream>\nusing namespace std;\nint main() {\n    long long x; cin >> x;\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    long long x; scanf(\"%lld\", &x);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        long x = sc.nextLong();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "123", expected_output: "321" },
      { input: "-123", expected_output: "-321" },
      { input: "1534236469", expected_output: "0" },
    ],
  },
  {
    id: "valid-parentheses",
    title: "Valid Parentheses",
    slug: "valid-parentheses",
    difficulty: "Easy",
    tags: ["string", "stack"],
    description: "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.\n\nAn input string is valid if open brackets are closed by the same type and in correct order.\n\nInput: A single string.\nOutput: 'true' or 'false'.",
    starter_code: {
      python: "s = input().strip()\n# Write your solution below\n",
      cpp: "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s; cin >> s;\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\n#include <string.h>\nint main() {\n    char s[10001];\n    scanf(\"%s\", s);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "()", expected_output: "true" },
      { input: "()[]{}", expected_output: "true" },
      { input: "(]", expected_output: "false" },
    ],
  },
  {
    id: "fizzbuzz",
    title: "FizzBuzz",
    slug: "fizzbuzz",
    difficulty: "Easy",
    tags: ["math", "string"],
    description: "Given an integer n, for each number from 1 to n:\n- Print 'FizzBuzz' if divisible by both 3 and 5\n- Print 'Fizz' if divisible by 3\n- Print 'Buzz' if divisible by 5\n- Otherwise print the number\n\nInput: A single integer n.\nOutput: n lines of FizzBuzz output.",
    starter_code: {
      python: "n = int(input())\n# Write your solution below\n",
      cpp: "#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int n; scanf(\"%d\", &n);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "5", expected_output: "1\n2\nFizz\n4\nBuzz" },
      { input: "15", expected_output: "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz" },
    ],
  },
  {
    id: "fibonacci-number",
    title: "Fibonacci Number",
    slug: "fibonacci-number",
    difficulty: "Easy",
    tags: ["math", "dynamic-programming"],
    description: "Given n, return the nth Fibonacci number. F(0) = 0, F(1) = 1, F(n) = F(n-1) + F(n-2).\n\nInput: A single integer n.\nOutput: The nth Fibonacci number.",
    starter_code: {
      python: "n = int(input())\n# Write your solution below\n",
      cpp: "#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int n; scanf(\"%d\", &n);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "0", expected_output: "0" },
      { input: "1", expected_output: "1" },
      { input: "10", expected_output: "55" },
    ],
  },
  {
    id: "maximum-subarray",
    title: "Maximum Subarray (Kadane's)",
    slug: "maximum-subarray",
    difficulty: "Medium",
    tags: ["array", "dynamic-programming"],
    description: "Given an integer array nums, find the subarray with the largest sum and return its sum (Kadane's algorithm).\n\nInput: First line is n, second line has n space-separated integers.\nOutput: The maximum subarray sum.",
    starter_code: {
      python: "n = int(input())\nnums = list(map(int, input().split()))\n# Write your solution below\n",
      cpp: "#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int n; scanf(\"%d\", &n);\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "9\n-2 1 -3 4 -1 2 1 -5 4", expected_output: "6" },
      { input: "1\n1", expected_output: "1" },
      { input: "5\n5 4 -1 7 8", expected_output: "23" },
    ],
  },
  {
    id: "binary-search",
    title: "Binary Search",
    slug: "binary-search",
    difficulty: "Easy",
    tags: ["array", "binary-search"],
    description: "Given a sorted array of integers and a target value, return the index of the target using binary search. If not found, return -1.\n\nInput: First line is n, second line has n sorted integers, third line is the target.\nOutput: Index of target or -1.",
    starter_code: {
      python: "n = int(input())\nnums = list(map(int, input().split()))\ntarget = int(input())\n# Write your solution below\n",
      cpp: "#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    int target; cin >> target;\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int n; scanf(\"%d\", &n);\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    int target; scanf(\"%d\", &target);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        int target = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "6\n-1 0 3 5 9 12\n9", expected_output: "4" },
      { input: "6\n-1 0 3 5 9 12\n2", expected_output: "-1" },
    ],
  },
  {
    id: "count-primes",
    title: "Count Primes (Sieve)",
    slug: "count-primes",
    difficulty: "Medium",
    tags: ["math", "sieve"],
    description: "Given an integer n, return the number of prime numbers that are strictly less than n.\n\nInput: A single integer n.\nOutput: Count of primes less than n.",
    starter_code: {
      python: "n = int(input())\n# Write your solution below\n",
      cpp: "#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int n; scanf(\"%d\", &n);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "10", expected_output: "4" },
      { input: "0", expected_output: "0" },
      { input: "1", expected_output: "0" },
    ],
  },
  {
    id: "merge-sorted-arrays",
    title: "Merge Sorted Arrays",
    slug: "merge-sorted-arrays",
    difficulty: "Easy",
    tags: ["array", "sorting", "two-pointer"],
    description: "Merge two sorted arrays into one sorted array and print the result.\n\nInput: First line is n, second line has n sorted integers, third line is m, fourth line has m sorted integers.\nOutput: Space-separated merged sorted array.",
    starter_code: {
      python: "n = int(input())\na = list(map(int, input().split()))\nm = int(input())\nb = list(map(int, input().split()))\n# Write your solution below\n",
      cpp: "#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    vector<int> a(n);\n    for (int i = 0; i < n; i++) cin >> a[i];\n    int m; cin >> m;\n    vector<int> b(m);\n    for (int i = 0; i < m; i++) cin >> b[i];\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int n; scanf(\"%d\", &n);\n    int a[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &a[i]);\n    int m; scanf(\"%d\", &m);\n    int b[m];\n    for (int i = 0; i < m; i++) scanf(\"%d\", &b[i]);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n];\n        for (int i = 0; i < n; i++) a[i] = sc.nextInt();\n        int m = sc.nextInt();\n        int[] b = new int[m];\n        for (int i = 0; i < m; i++) b[i] = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "3\n1 3 5\n3\n2 4 6", expected_output: "1 2 3 4 5 6" },
      { input: "2\n1 2\n2\n3 4", expected_output: "1 2 3 4" },
    ],
  },
  {
    id: "number-of-islands",
    title: "Number of Islands (BFS/DFS)",
    slug: "number-of-islands",
    difficulty: "Hard",
    tags: ["array", "graph", "bfs", "matrix"],
    description: "Given a 2D grid map of '1's (land) and '0's (water), count the number of islands. An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.\n\nInput: First line is rows and cols, followed by rows lines of space-separated integers.\nOutput: Number of islands.",
    starter_code: {
      python: "r, c = map(int, input().split())\ngrid = [list(map(int, input().split())) for _ in range(r)]\n# Write your solution below\n",
      cpp: "#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    int r, c; cin >> r >> c;\n    vector<vector<int>> grid(r, vector<int>(c));\n    for (int i = 0; i < r; i++) for (int j = 0; j < c; j++) cin >> grid[i][j];\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int r, c; scanf(\"%d %d\", &r, &c);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int r = sc.nextInt();\n        int c = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "3 3\n1 1 0\n0 1 0\n0 0 1", expected_output: "2" },
      { input: "2 2\n1 0\n0 1", expected_output: "2" },
    ],
  },
  {
    id: "coin-change",
    title: "Coin Change",
    slug: "coin-change",
    difficulty: "Medium",
    tags: ["dynamic-programming"],
    description: "You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money. Return the fewest number of coins that you need to make up that amount. If impossible, return -1.\n\nInput: First line is n (number of coins), second line has n coins, third line is amount.\nOutput: Minimum number of coins or -1.",
    starter_code: {
      python: "n = int(input())\ncoins = list(map(int, input().split()))\namount = int(input())\n# Write your solution below\n",
      cpp: "#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    vector<int> coins(n);\n    for (int i = 0; i < n; i++) cin >> coins[i];\n    int amount; cin >> amount;\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int n; scanf(\"%d\", &n);\n    int coins[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &coins[i]);\n    int amount; scanf(\"%d\", &amount);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] coins = new int[n];\n        for (int i = 0; i < n; i++) coins[i] = sc.nextInt();\n        int amount = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "4\n1 5 6 9\n11", expected_output: "2" },
      { input: "1\n2\n3", expected_output: "-1" },
    ],
  },
  {
    id: "climbing-stairs",
    title: "Climbing Stairs",
    slug: "climbing-stairs",
    difficulty: "Easy",
    tags: ["dynamic-programming", "math"],
    description: "You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?\n\nInput: A single integer n.\nOutput: Total distinct ways.",
    starter_code: {
      python: "n = int(input())\n# Write your solution below\n",
      cpp: "#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int n; scanf(\"%d\", &n);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "2", expected_output: "2" },
      { input: "3", expected_output: "3" },
      { input: "4", expected_output: "5" },
    ],
  },
  {
    id: "longest-common-prefix",
    title: "Longest Common Prefix",
    slug: "longest-common-prefix",
    difficulty: "Easy",
    tags: ["string"],
    description: "Write a function to find the longest common prefix string amongst an array of strings. If there is no common prefix, print an empty line.\n\nInput: First line is n, followed by n strings on the second line.\nOutput: The longest common prefix.",
    starter_code: {
      python: "n = int(input())\nwords = input().split()\n# Write your solution below\n",
      cpp: "#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    vector<string> words(n);\n    for (int i = 0; i < n; i++) cin >> words[i];\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int n; scanf(\"%d\", &n);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "3\nflower flow flight", expected_output: "fl" },
      { input: "3\ndog racecar car", expected_output: "" },
    ],
  },
  {
    id: "rotate-array",
    title: "Rotate Array",
    slug: "rotate-array",
    difficulty: "Medium",
    tags: ["array"],
    description: "Given an array, rotate the array to the right by k steps, where k is non-negative.\n\nInput: First line is n, second line has n integers, third line is k.\nOutput: Space-separated rotated array.",
    starter_code: {
      python: "n = int(input())\nnums = list(map(int, input().split()))\nk = int(input())\n# Write your solution below\n",
      cpp: "#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    int k; cin >> k;\n    // Write your solution below\n    return 0;\n}\n",
      c: "#include <stdio.h>\nint main() {\n    int n; scanf(\"%d\", &n);\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    int k; scanf(\"%d\", &k);\n    // Write your solution below\n    return 0;\n}\n",
      java: "import java.util.Scanner;\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        int k = sc.nextInt();\n        // Write your solution below\n    }\n}\n",
    },
    testcases: [
      { input: "5\n1 2 3 4 5\n2", expected_output: "4 5 1 2 3" },
      { input: "3\n1 2 3\n1", expected_output: "3 1 2" },
    ],
  },
];
